HotelManagementSystem/Models/SearchViewModels.cs
using System;
using System.Collections.Generic;
using System.Data.SqlClient;

namespace HotelManagementSystem.Models
{
    public class SearchResult
    {
        public string roomType { get; set; }
        public int count { get; set; }
        public double pricePerRoom { get; set; }
    }

    public class BookingDates
    {
        public DateTime checkInDate { get; set; }
        public DateTime checkOutDate { get; set; }
        
    }

    public class RoomBookingDetails
    {
        public string roomType { get; set; }
        public int count { get; set; }
    }

    public class SearchViewModels
    {
        static readonly string connectionString = "Server=localhost;Database=master;Trusted_connection = True;";
        public List<SearchResult> searchResult { get; set; }
        public BookingDates bookingDates { get; set; }
        public RoomBookingDetails roomBookingDetails { get; set; }
       

        public void GetSearchResult(DateTime checkInDate, DateTime checkOutDate, string roomType, int roomCount)
        {
            
            if (checkInDate == null || checkOutDate == null)
                return;

            searchResult = new List<SearchResult>();
            bookingDates = new BookingDates();
            roomBookingDetails = new RoomBookingDetails();

            bookingDates.checkInDate = checkInDate.Add(new TimeSpan(14, 0, 0));
            bookingDates.checkOutDate = checkOutDate.Add(new TimeSpan(11, 0, 0));

            roomBookingDetails.roomType = roomType;
            roomBookingDetails.count = roomCount;

            roomType += "%";

            string queryString = @"SELECT r.roomType, COUNT(DISTINCT r.roomNumber), r.price
	                                FROM master.[dbproject].Room r LEFT JOIN master.[dbproject].OccupancyDates od ON (r.id = od.roomId)
	                                WHERE ((od.inDate > @checkOutDate
		                                  OR od.outDate < @checkInDate)
		                                OR od.roomId IS NULL )                                       
		                                AND r.roomType like @roomType   
	                                GROUP BY r.roomType, r.price
	                                HAVING COUNT(*) >= @roomCount;";

            SqlParameter[] param = new SqlParameter[4];
            param[0] = new SqlParameter("@checkInDate", checkInDate);
            param[1] = new SqlParameter("@checkOutDate", checkOutDate);
            param[2] = new SqlParameter("@roomType", roomType);
            param[3] = new SqlParameter("@roomCount", roomCount);

            using (SqlConnection connection = new SqlConnection(connectionString))
            {
                using (SqlCommand command = new SqlCommand(queryString, connection))
                {
                    command.Connection.Open();
                    if (param != null)
                        command.Parameters.AddRange(param);

                    using (SqlDataReader myReader = command.ExecuteReader())
                    {
                       
                        while (myReader.Read())
                        {
                            SearchResult sr = new SearchResult();

                            sr.roomType = myReader.GetString(0);
                            sr.count = myReader.GetInt32(1);
                            sr.pricePerRoom = myReader.GetDouble(2);
                            searchResult.Add(sr);
                        }
                    }
                }
            }
        }

    }
}

HotelManagementSystem/Controllers/Guest/BookController.cs
using HotelManagementSystem.Models;
using System;
using System.Web.Mvc;

namespace HotelManagementSystem.Controllers
{
    public class BookController : Controller
    {
        //[HttpPost]
        public ActionResult BookRoom(string bookingDate, string roomType, int roomCount, double roomPrice)
        {
            string[] bookinDates = bookingDate.Split(' ');
            DateTime checkInDate = Convert.ToDateTime(bookinDates[0]).Add(new TimeSpan(14, 0, 0));
            DateTime checkOutDate = Convert.ToDateTime(bookinDates[1]).Add(new TimeSpan(11, 0, 0));

            BookViewModel bvmObj = new BookViewModel(new RoomDetail(checkInDate, checkOutDate, roomType.Trim(), roomCount, roomPrice));

            return View(bvmObj);
        }

        [HttpPost]
        public ActionResult ConfirmBooking(BookViewModel bvmObj)
        {
            if (bvmObj != null)
            {
                BookingDetail bdObj = bvmObj.AddBookingDetails();
                return RedirectToAction("BookingDetails", bdObj);
                //return View(bdObj);
            }

            return RedirectToAction("BookingDetails", new BookingDetail());

        }

        public ActionResult BookingDetails(BookingDetail bdObj)
        {
            string body = $"<h2>Thank you for your booking...!!!</h2> <hr><h4>Booking Details</h4> Confirmation Code: <b>{bdObj.confirmationCode}</b> <br> Check-in Date: <b>{bdObj.checkInDate}</b> <br> Check-out Date: <b>{bdObj.checkOutDate}</b> <br> Room-Type: <b>{bdObj.roomType}</b> <br> Room Count: <b>{bdObj.roomCount}</b> <br> Amount Paid: <b>{bdObj.totalAmountPaid}</b>";
            SMTP.SMTP.SendSMTPMail(bdObj.emailAddr, body);
            return View(bdObj);
        }
    }
}

HotelManagementSystem/Controllers/Guest/SearchController.cs
using HotelManagementSystem.Models;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace HotelManagementSystem.Controllers
{
    public class SearchController : Controller
    {
        public ActionResult Index()
        {
            return View();
        }

        // GET: Search
        public ActionResult SearchRoom()
        {
            return View(new SearchViewModels());
        }

        [HttpPost]
        public ActionResult SearchRoom(DateTime checkIn, DateTime checkOut, string roomType, int roomCount)
        {
            SearchViewModels obj = new SearchViewModels();
            obj.GetSearchResult(checkIn, checkOut, roomType, roomCount);
            return View(obj);
        }

        
      
    }
}

HotelManagementSystem/Views/Guest/Search/SearchRoom.cshtml
@model HotelManagementSystem.Models.SearchViewModels

<style>
    form {
        /*border: 2px solid grey;
        padding: 35px 40px 10px 30px;*/
        margin: 10px;
        width: auto;
    }
</style>

<div>
    @using (Html.BeginForm("SearchRoom", "Search", FormMethod.Post))
    {
        <fieldset>
            <legend>Search Available Room</legend>

            <form id="searchRoom-form" name="searchRoom-form">
                <div class="form-group row" id="checkIn1">
                    <label class="col-lg-2">Check-In Date:</label>
                    <div class="col-lg-10">
                        @if (Model.bookingDates != null)
                        {
                            ViewBag.checkInDate = Model.bookingDates.checkInDate.ToShortDateString();
                        }
                        @*<span class="glyphicon glyphicon-warning-sign form-control-feedback"></span>*@
                        <input type="text" class="form-control" id="checkIn" name="checkIn" value="@ViewBag.checkInDate">


                        <p class="help-block">Check In after 14:00 hrs</p>
                    </div>
                </div>

                <div class="form-group row" id="checkOut1">
                    <label class="col-lg-2">Check-Out Date:</label>
                    <div class="col-lg-10">
                        @if (Model.bookingDates != null)
                        {
                            ViewBag.checkOutDate = Model.bookingDates.checkOutDate.ToShortDateString();
                        }
                        <input type="text" class="form-control" id="checkOut" name="checkOut" value="@ViewBag.checkOutDate">
                        <p class="help-block">Check Out before 11:00 hrs</p>
                    </div>
                </div>

                <div class="form-group row">
                    <label class="col-lg-2">Room Type:</label>
                    <div class="col-lg-10">
                        <select class="form-control" id="roomType" name="roomType">
                            <option></option>
                            <option>Premium</option>
                            <option>Deluxe</option>
                            <option>Super Deluxe</option>
                            <option>Suite</option>
                        </select>
                    </div>
                </div>



                <div class="form-group row">
                    <label class="col-lg-2">Room Count:</label>
                    <div class="col-lg-10">
                        <select class="form-control" name="roomCount">
                            <option>1</option>
                            <option>2</option>
                            <option>3</option>
                            <option>4</option>
                            <option>5</option>
                            <option>6</option>
                            <option>7</option>
                            <option>8</option>
                        </select>
                    </div>
                </div>

                <div class="form-group row">
                    <div class="col-lg-offset-2 col-lg-10">
                        <input type="submit" class="btn btn-primary btn-block" value="Search Room(s)" />
                    </div>
                </div>

            </form>

        </fieldset>
    }

    <script>
        $(function () {
            var dateFormat = "mm/dd/yy",
              from = $("#checkIn")
                .datepicker({
                    minDate: 0,
                    defaultDate: "+1w",
                    changeMonth: true,
                    numberOfMonths: 2,
                    onSelect: function (selected) {
                        var dt = new Date(selected);
                        dt.setDate(dt.getDate() + 1);
                        $("#checkOut").datepicker("option", "minDate", dt);
                    }
                })
                .on("change", function () {
                    to.datepicker("option", "minDate", getDate(this) + 1);
                }),
              to = $("#checkOut").datepicker({
                  minDate: 1,
                  defaultDate: "+1w",
                  changeMonth: true,
                  numberOfMonths: 2,
                  onSelect: function (selected) {
                      var dt = new Date(selected);
                      dt.setDate(dt.getDate() - 1);
                      $("#checkIn").datepicker("option", "maxDate", dt);
                  }
              })
              .on("change", function () {
                  from.datepicker("option", "maxDate", getDate(this) - 1);
              });

            function getDate(element) {
                var date;
                try {
                    date = $.datepicker.parseDate(dateFormat, element.value);
                } catch (error) {
                    date = null;
                }

                return date;
            }

            $("form").submit(function (e) {
                event = event || window.event || event.srcElement;

                var checkInDate = $('#checkIn').val();
                var checkOutDate = $('#checkOut').val();
                var prevent = false;

                if (checkInDate == "") {
                    $('#checkIn1').addClass('has-error');
                    $('#checkIn').addClass('input-group-focus')
                    $('#checkIn').effect("highlight", {}, 1000);
                    prevent = true;
                }
                else {
                    $('#checkIn1').removeClass('has-error');
                    $('#checkIn').removeClass('form-control-warning')
                }

                if (checkOutDate == "") {
                    $('#checkOut1').addClass('has-error');
                    $('#checkOut').addClass('form-control-warning')
                    $('#checkOut').effect("highlight", {}, 1000);
                    prevent = true;
                }
                else {
                    $('#checkOut1').removeClass('has-error');
                    $('#checkOut').removeClass('form-control-warning')
                }

                if (prevent == true) {
                    event.preventDefault();
                }
            });
        });
    </script>

    @if (Model != null && Model.searchResult != null)
            {
        <fieldset>
            <legend>Available Room(s)</legend>
            <table class="table table-bordered table-hover">
                <thead class="thead-inverse">
                    <tr>
                        <th>Room Type</th>
                        <th>Room(s) Available</th>
                        <th>Price per room($)</th>
                        <th></th>
                    </tr>
                </thead>
                <tbody>
                    @foreach (var result in Model.searchResult)
                    {
                        <tr>
                            <td>
                                @Html.DisplayFor(modelItem => result.roomType)
                            </td>
                            <td>
                                @Html.DisplayFor(modelItem => result.count)
                            </td>
                            <td>
                                @Html.DisplayFor(modelItem => result.pricePerRoom)
                            </td>
                            <td><button type="button" class="book btn btn-primary btn-block">Book</button></td>
                        </tr>

                    }
                </tbody>
            </table>
        </fieldset>
    }
    <script>
        $('.book').click(function () {
            var roomType = $(this).closest("tr").find('td:eq(0)').text().trim(" ");
            var roomCount = $(this).closest("tr").find('td:eq(1)').text().trim(" ");
            var roomPrice = $(this).closest("tr").find('td:eq(2)').text().trim(" ");


            var url = "@Url.Action("BookRoom", "Book", new { bookingDate = @ViewBag.checkInDate + " " + @ViewBag.checkOutDate })";

            url = url + "&roomType=" + roomType + "&roomCount=" + roomCount + "&roomPrice=" + roomPrice;
            window.location.href = url;


        });
    </script>


</div>