HotelManagementSystem/Controllers/Receptionist/CheckOutController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using HotelManagementSystem.Models;

namespace HotelManagementSystem.Controllers
{
    public class CheckOutController : Controller
    {
        // GET: CheckOut
        public ActionResult CheckOut()
        {
            ViewBag.Message = "CheckOut a guest";
            ViewBag.Message2 = "Enter the room number and check out date to proceed:";
            return View(new CheckOut());
        }

        [HttpPost]
        public ActionResult CheckOut(CheckOut obj)
        {
            obj.CheckOutFromRoom();
            if (obj.message != null)
            {
                ViewBag.Message = obj.message;
                return View(obj);
            }

            else
            {
                ViewBag.Message = "CheckOut successfully done";
                return RedirectToAction("ReceiptPage", obj);
            }
        }

        public ActionResult ReceiptPage(CheckOut coObj)
        {
            coObj.GenerateReceipt();
            return View(coObj);
        }
    }
}

HotelManagementSystem/Controllers/Receptionist/RoomExpenseController.cs
using HotelManagementSystem.Models;
using System;
using System.Web.Mvc;

namespace HotelManagementSystem.Controllers.Receptionist
{
    public class RoomExpenseController : Controller
    {
        // GET: RoomExpense
        public ActionResult Index()
        {    
            return View(new RoomExpense());
        }

        [HttpPost]
        public ActionResult Index(RoomExpense reObj)
        { 
            return RedirectToAction("RoomExpenseFeedback", new {rowsAdded = reObj.AddExpense(), roomNum= reObj.roomNumber, description = reObj.description});
        }

        public ActionResult RoomExpenseFeedback(int rowsAdded, int roomNum, string description)
        {
            ViewBag.description = description;
            ViewBag.rowsAdded = rowsAdded;
            ViewBag.roomNum = roomNum;

            return View();
        }

    }
}

HotelManagementSystem/Controllers/Receptionist/SearchBookingController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using HotelManagementSystem.Models;

namespace HotelManagementSystem.Controllers
{
    public class SearchBookingController : Controller
    {
        static BookingDetails obj { get; set; }

        // GET: SearchBooking
        public ActionResult Index()
        {
            return View();
        }

        [HttpPost]
        public ActionResult Index(string confirmationCode)
        {
            obj = new BookingDetails();

            obj.GetBookingDetails(confirmationCode);

            obj.resultData.roomCountCheckedIn = obj.GetRoomCountCheckedIn(confirmationCode);

            return View(obj);
        }

        [HttpPost]
        public ActionResult SearchEmptyRoom()
        {
            int roomCount = obj.resultData.roomCount;
            string confirmationCode = obj.resultData.confirmationCode;

            SearchEmptyRoom serObj = new SearchEmptyRoom(confirmationCode, roomCount);

            if (serObj.checkedInRoomCount == roomCount)
            {
                ViewBag.Message = "CheckIn successfully completed for all room(s)";
                return View();
            }

            ViewBag.Message = "Available Rooms";

            serObj.GetEmptyRooms(confirmationCode);

            return View(serObj);
        }

        [HttpPost]
        public ActionResult CheckIn(int roomNumber = 0)
        {
            SearchEmptyRoom serObj = new SearchEmptyRoom();

            serObj.CheckInRoom(obj.resultData.confirmationCode, roomNumber);

            if (serObj.message == null)
            {
                ViewBag.Message = "CheckIn Done successfuly for room number: " + roomNumber;
            }
            else
            {
                ViewBag.Message = serObj.message;
            }

            return View(serObj);
        }
    }
}

HotelManagementSystem/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html>
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Hotel Management System</title>
    @Styles.Render("~/Content/css")
    @Scripts.Render("~/bundles/modernizr")

    <link rel="stylesheet" href="//code.jquery.com/ui/1.12.1/themes/base/jquery-ui.css">
    <script src="https://code.jquery.com/jquery-1.12.4.js"></script>
    <script src="https://code.jquery.com/ui/1.12.1/jquery-ui.js"></script>
    <script type="text/javascript" src="http://ajax.aspnetcdn.com/ajax/jquery.validate/1.7/jquery.validate.min.js"></script>

    <script src="https://cdnjs.cloudflare.com/ajax/libs/moment.js/2.13.0/moment.min.js"></script>
    <script src="https://cdnjs.cloudflare.com/ajax/libs/bootstrap-datetimepicker/4.17.37/js/bootstrap-datetimepicker.min.js"></script>
    
    <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/css/bootstrap.min.css">
    <script src="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/js/bootstrap.min.js"></script>
    @Scripts.Render("~/bundles/bootstrap")
    @RenderSection("scripts", required: false)

</head>
<body>
    <div class="navbar navbar-inverse navbar-fixed-top">
        <div class="container">
            <div class="navbar-header">
                <button type="button" class="navbar-toggle" data-toggle="collapse" data-target=".navbar-collapse">
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                </button>
                @Html.ActionLink("Hotel Management System", "Index", "Home", new { area = "" }, new { @class = "navbar-brand" })
            </div>
            <div class="navbar-collapse collapse">
                <ul class="nav navbar-nav hide" id="Receptionist">
                    <li class="nav">@Html.ActionLink("Search Booking", "Index", "SearchBooking")</li>
                    <li class="nav">@Html.ActionLink("Check Out", "CheckOut", "CheckOut")</li>
                    <li class="nav">@Html.ActionLink("Add Expense", "Index", "RoomExpense")</li>                  
                </ul>
            </div>
        </div>
    </div>
    <div class="container body-content">
        @RenderBody()
    </div>
    <script>
        
        $(function () {
            var url = $(location).attr("href");

            if (url.includes("RoomExpense") || url.includes("CheckOut") || url.includes("SearchBooking") || url.includes("CheckIn") || url.includes("SearchEmptyRoom")) {
                $("#Receptionist").removeClass("hide");          
            }
            else {
                $("#Receptionist").addClass("hide");
            }

            //$(".navbar-nav li .nav").click(function (e) {
            //    e.preventDefault();
            //    $(".navbar-nav li a.active").removeClass("active"); //Remove any "active" class  
            //    $(this).addClass("active"); //Add "active" class to selected tab  
            //    $(activeTab).show(); //Fade in the active content  
            //});
        });
    </script>
 
</body>
</html>